### ISSUE TITLE
[问题] 需要更新下载源，中国大陆地区用户无法进行下载。

### ISSUE THREAD

**Issue by scratchfens481** [RuizeSun/Yilianfang#3]
**整体描述**
需要更新下载源，中国大陆用户无法进行下载

**复原过程**
1. 打开程序
2. 下载相关文件过慢或无法下载，必须打开魔法

**修复建议**
建议更换文件下载源

**Comment by RuizeSun** [comment]
我对你的表述进行了格式化。**关于下载源的问题将会在后几个版本中修复**，十分感谢你对该问题的提出。当解决问题后，将会关闭该 Issue 。

**Comment by RuizeSun** [comment]
**问题已在 测试版 d1019a 中修复**，所以我将关闭该 Issue 。
